---

###############################
# OpenShift Pre-Requisites

# Ensure the 'docker_storage_block_device' is correctly populated for all nodes
- hosts: nodes
  tasks:
    - set_fact:
        docker_storage_block_device: "{{ hostvars['localhost'].docker_storage_block_device }}"

# - subscribe hosts
# - prepare docker
# - other prep (install additional packages, etc.)
#
- hosts: OSEv3
  roles:
    - { role: ../../galaxy/openshift-ansible-contrib/roles/subscription-manager, when: hostvars.localhost.rhsm_register, tags: 'subscription-manager', ansible_sudo: true }
    - { role: docker-fix-37, tags: 'docker' }
    - { role: ../../galaxy/infra-ansible/roles/config-versionlock,
              when: docker_version is defined,
              versionlock_packages: '[ "docker-{{ docker_version }}",
                                       "docker-rhel-push-plugin-{{ docker_version }}",
                                       "docker-client-{{ docker_version }}",
                                       "docker-common-{{ docker_version }}" ]'
      }
    - { role: ../../galaxy/openshift-ansible-contrib/roles/openshift-prep, tags: 'openshift-prep' }

# Ensure the CNS / glusterFS facts are correctly populated for all CNS nodes
- hosts: glusterfs
  tasks:
    - set_fact:
       glusterfs_devices:
         - "{{ hostvars['localhost'].cns_node_glusterfs_volume }}"

