---

- hosts: localhost
  pre_tasks:
    - import_tasks: ../prep-inventory.yml
  roles:
    - role: manage-aws-infra
      operation: inventory_gen_e2c

- hosts: localhost
  pre_tasks:
    - import_tasks: ../prep-inventory.yml
  roles:
    - role: manage-aws-infra
      operation: deploy

- name: Refresh Server inventory
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - meta: refresh_inventory

- hosts: localhost
  pre_tasks:
    - import_tasks: ../prep-inventory.yml
  roles:
    - role: manage-aws-infra
      operation: inventory_gen_hosts

- name: Refresh Server inventory
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - meta: refresh_inventory

- hosts: cluster_hosts
  gather_facts: false
  tasks:
    - name: Debug hostvar
      debug:
        msg: "{{ hostvars[inventory_hostname] }}"
        verbosity: 2
    - import_role:
        name: ../../../galaxy/infra-ansible/roles/update-host
        tasks_from: wait-for-host

- hosts: cluster_hosts
  tasks:
    - name: Set Openshift Hostnames
      set_fact:
        openshift_hostname: "{{ ec2_private_dns_name }}"
        openshift_public_hostname: "{{ ec2_public_dns_name }}"

