---

#
# This is an example inventory for OpenShift cluster content that will be
# automatically loaded up by the 'openshift-applier' at the end of the
# OpenShift Cluster provisioning
#
# Please check out the OpenShift Applier repo for more details:
#   https://github.com/redhat-cop/openshift-applier
# 

openshift_cluster_content:
- object: namespace
  content:
  - name: "cakephp-development"
    file: "{{ inventory_dir }}/../files/cakephp/namespace/development.yml"
  - name: "cakephp-stage"
    file: "{{ inventory_dir }}/../files/cakephp/namespace/stage.yml"
  - name: "cakephp-production"
    file: "{{ inventory_dir }}/../files/cakephp/namespace/production.yml"
- object: builds
  content:
  - name: "cakephp"
    template: "{{ inventory_dir }}/../files/cakephp/build/template.yml"
    params: "{{ inventory_dir }}/../files/cakephp/build/development/params"
- object: deployments
  content:
  - name: "jenkins"
    namespace: "cakephp-dev"
    template: "openshift//jenkins-ephemeral"
    params: "{{ inventory_dir }}/../files/cakephp/deployment/development/jenkins-params"
  - name: "cakephp-development"
    template: "{{ inventory_dir }}/../files/cakephp/deployment/template.yml"
    params: "{{ inventory_dir }}/../files/cakephp/deployment/development/params"
  - name: "cakephp-stage"
    template: "{{ inventory_dir }}/../files/cakephp/deployment/template.yml"
    params: "{{ inventory_dir }}/../files/cakephp/deployment/stage/params"
  - name: "cakephp-development"
    template: "{{ inventory_dir }}/../files/cakephp/deployment/template.yml"
    params: "{{ inventory_dir }}/../files/cakephp/deployment/production/params"
