---

required_packages:
  - wget
  - git
  - net-tools
  - bind-utils
  - iptables-services
  - bridge-utils
  - bash-completion
  - kexec-tools
  - sos 
  - psacct
  - atomic-openshift-excluder
  - atomic-openshift-docker-excluder
