---

- name: "Start with a clean list of records"
  set_fact:
    a_records: []
    nsupdate_servers: []

- name: "Set the DNS zone to use"
  set_fact:
    nsupdate_zone: "{{ nsupdate.zone | default(full_dns_domain) }}"

- name: "Generate list of A records"
  set_fact:
    a_records: "{{ a_records +
                   [{
                      'type': 'A',
                      'record': (hostvars[item]['ansible_fqdn'] | replace('.' + nsupdate_zone, '')),
                      'value': hostvars[item][nsupdate.view + '_v4']
                   }]
                 }}"
  with_items:
    - "{{ groups['cluster_hosts'] }}"

- name: "Add wildcard records to the A records for infrahosts"
  set_fact:
    a_records: "{{ a_records +
                   [{
                      'type': 'A',
                      'record': '*.' + (openshift_master_default_subdomain | replace('.' + nsupdate_zone, '')),
                      'value': hostvars[item][nsupdate.view + '_v4']
                   }]
                }}"
  when:
    - openshift_master_default_subdomain is defined
    - openshift_master_default_subdomain|trim != ''
  with_items:
    - "{{ groups['infra_hosts'] }}"

- name: "Set master ip to be used (single master)"
  set_fact:
    master_ip: "{{ hostvars[groups.masters[0]][nsupdate.view + '_v4'] }}"
  run_once: true
  delegate_to: "{{ groups['masters'] | first }}"
  when:
    - (groups['masters'] | length == 1)

- name: "Set master ip to be used (multi master)"
  set_fact:
    master_ip: "{{ hostvars[groups.lb[0]][nsupdate.view + '_v4'] }}"
  run_once: true
  delegate_to: "{{ groups['masters'] | first }}"
  when:
    - (groups['masters'] | length > 1)

- name: "Add public master cluster hostname records to the A records"
  set_fact:
    a_records: "{{ a_records +
                   [{
                      'type': 'A',
                      'record': (hostvars[groups.masters[0]].openshift_master_cluster_public_hostname | replace(nsupdate_zone, ''))[:-1],
                      'value': master_ip
                   }]
                }}"
  when:
    - hostvars[groups.masters[0]].openshift_master_cluster_public_hostname is defined

- name: "Generate the nsupdate server list"
  set_fact:
    nsupdate_servers: "{{ nsupdate_servers +
                         [{
                           'server': item.server,
                           'key_name': item.key_name,
                           'key_secret': item.key_secret,
                           'key_algorithm': (item.key_algorithm|lower)
                         }]
                       }}"
  with_items:
    - "{{ nsupdate.server_list }}"

- name: "Generate the Add section for DNS for all nsupdate servers"
  set_fact:
    dns_view:
      - name: "{{ nsupdate.view }}"
        zones:
          - dns_domain: "{{ nsupdate.zone }}"
            nsupdate: "{{ nsupdate_servers }}"
            entries: "{{ a_records }}"

- name: "Add to 'dns_data' dictionary"
  set_fact:
    dns_data:
      views: "{{ dns_data.views + dns_view }}"
