---

- hosts: localhost
  pre_tasks:
    - import_tasks: ../prep-inventory.yml
    - import_tasks: prep-env.yml
  tasks:
    - import_role:
        name: ../../../galaxy/openshift-ansible/roles/openshift_openstack
        tasks_from: provision.yml
      vars:
        openshift_openstack_stack_name: "{{ env_id }}.{{ dns_domain }}"
        openshift_openstack_public_dns_domain: "{{ dns_domain }}"
        openshift_openstack_full_dns_domain: "{{ openshift_openstack_stack_name }}"
        openshift_openstack_dns_nameservers: "{{ dns_nameservers }}"
        openshift_openstack_subnet_cidr: "{{ openstack_subnet_prefix }}.0/24"
        openshift_openstack_pool_start: "{{ openstack_subnet_prefix }}.2"
        openshift_openstack_pool_end: "{{ openstack_subnet_prefix }}.254"
        openshift_openstack_keypair_name: "{{ openstack_ssh_public_key }}"
        openshift_openstack_master_flavor: "{{ openstack_master_flavor | default( openstack_default_flavor ) }}"
        openshift_openstack_etcd_flavor: "{{ openstack_etcd_flavor | default( openstack_default_flavor ) }}"
        openshift_openstack_node_flavor: "{{ openstack_node_flavor | default( openstack_default_flavor ) }}"
        openshift_openstack_infra_flavor: "{{ openstack_infra_flavor | default( openstack_default_flavor ) }}"
        openshift_openstack_lb_flavor: "{{ openstack_lb_flavor | default('m1.small') }}"
        openshift_openstack_external_network_name: "{{ openstack_external_network_name }}"
        openshift_openstack_num_masters: "{{ openstack_num_masters }}"
        openshift_openstack_num_etcd: "{{ openstack_num_etcd | default(0) }}"
        openshift_openstack_num_nodes: "{{ openstack_num_nodes }}"
        openshift_openstack_num_infra: "{{ openstack_num_infra }}"
        openshift_openstack_master_volume_size: "{{ docker_volume_size }}"
        openshift_openstack_etcd_volume_size: "{{ docker_volume_size }}"
        openshift_openstack_node_volume_size: "{{ docker_volume_size }}"
        openshift_openstack_infra_volume_size: "{{ docker_volume_size }}"
        openshift_openstack_default_flavor: "{{ openstack_default_flavor }}"
        openshift_openstack_default_image_name: "{{ openstack_default_image_name }}"
        l_hostname_domain_suffix: ".{{ openshift_openstack_stack_name }}"

- name: Refresh Server inventory
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - meta: refresh_inventory

- hosts: cluster_hosts
  gather_facts: false
  tasks:
    - name: Debug hostvar
      debug:
        msg: "{{ hostvars[inventory_hostname] }}"
        verbosity: 2
    - import_role:
        name: ../../../galaxy/infra-ansible/roles/update-host
        tasks_from: wait-for-host

- import_playbook: post-provision.yml

